# Generated by Django 5.2.8 on 2025-11-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_edit_author', 'Can edit author'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Can edit book'),)},
        ),
    ]
